name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      name: Set up ruby
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake